
package juntadeandalucia.cice.pfirma.query.v2;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QueryServiceService", targetNamespace = "urn:juntadeandalucia:cice:pfirma:query:v2.0", wsdlLocation = "META-INF/wsdl/QueryService.wsdl")
public class QueryServiceService
    extends Service
{

    private final static URL QUERYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException QUERYSERVICESERVICE_EXCEPTION;
    private final static QName QUERYSERVICESERVICE_QNAME = new QName("urn:juntadeandalucia:cice:pfirma:query:v2.0", "QueryServiceService");

    static {
        QUERYSERVICESERVICE_WSDL_LOCATION = juntadeandalucia.cice.pfirma.query.v2.QueryServiceService.class.getClassLoader().getResource("META-INF/wsdl/QueryService.wsdl");
        WebServiceException e = null;
        if (QUERYSERVICESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/QueryService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        QUERYSERVICESERVICE_EXCEPTION = e;
    }

    public QueryServiceService() {
        super(__getWsdlLocation(), QUERYSERVICESERVICE_QNAME);
    }

    public QueryServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUERYSERVICESERVICE_QNAME, features);
    }

    public QueryServiceService(URL wsdlLocation) {
        super(wsdlLocation, QUERYSERVICESERVICE_QNAME);
    }

    public QueryServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUERYSERVICESERVICE_QNAME, features);
    }

    public QueryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QueryService
     */
    @WebEndpoint(name = "QueryServicePort")
    public QueryService getQueryServicePort() {
        return super.getPort(new QName("urn:juntadeandalucia:cice:pfirma:query:v2.0", "QueryServicePort"), QueryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryService
     */
    @WebEndpoint(name = "QueryServicePort")
    public QueryService getQueryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:juntadeandalucia:cice:pfirma:query:v2.0", "QueryServicePort"), QueryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUERYSERVICESERVICE_EXCEPTION!= null) {
            throw QUERYSERVICESERVICE_EXCEPTION;
        }
        return QUERYSERVICESERVICE_WSDL_LOCATION;
    }

}
