
package com.sap.document.sap.soap.functions.mc_style;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Z_WS_PE_ACT_JORNADA_NOMINA", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "META-INF/wsdl/jornadaNomina.wsdl")
public class ZWSPEACTJORNADANOMINA_Service
    extends Service
{

    private final static URL ZWSPEACTJORNADANOMINA_WSDL_LOCATION;
    private final static WebServiceException ZWSPEACTJORNADANOMINA_EXCEPTION;
    private final static QName ZWSPEACTJORNADANOMINA_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_ACT_JORNADA_NOMINA");

    static {
        ZWSPEACTJORNADANOMINA_WSDL_LOCATION = com.sap.document.sap.soap.functions.mc_style.ZWSPEACTJORNADANOMINA_Service.class.getClassLoader().getResource("META-INF/wsdl/jornadaNomina.wsdl");
        WebServiceException e = null;
        if (ZWSPEACTJORNADANOMINA_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/jornadaNomina.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ZWSPEACTJORNADANOMINA_EXCEPTION = e;
    }

    public ZWSPEACTJORNADANOMINA_Service() {
        super(__getWsdlLocation(), ZWSPEACTJORNADANOMINA_QNAME);
    }

    public ZWSPEACTJORNADANOMINA_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEACTJORNADANOMINA_QNAME, features);
    }

    public ZWSPEACTJORNADANOMINA_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEACTJORNADANOMINA_QNAME);
    }

    public ZWSPEACTJORNADANOMINA_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEACTJORNADANOMINA_QNAME, features);
    }

    public ZWSPEACTJORNADANOMINA_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEACTJORNADANOMINA_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEACTJORNADANOMINA
     */
    @WebEndpoint(name = "Z_WS_PE_ACT_JORNADA_NOMINA")
    public ZWSPEACTJORNADANOMINA getZWSPEACTJORNADANOMINA() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_ACT_JORNADA_NOMINA"), ZWSPEACTJORNADANOMINA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEACTJORNADANOMINA
     */
    @WebEndpoint(name = "Z_WS_PE_ACT_JORNADA_NOMINA")
    public ZWSPEACTJORNADANOMINA getZWSPEACTJORNADANOMINA(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_ACT_JORNADA_NOMINA"), ZWSPEACTJORNADANOMINA.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEACTJORNADANOMINA_EXCEPTION!= null) {
            throw ZWSPEACTJORNADANOMINA_EXCEPTION;
        }
        return ZWSPEACTJORNADANOMINA_WSDL_LOCATION;
    }

}
