
package juntadeandalucia.cice.pfirma.admin.v2;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import juntadeandalucia.cice.pfirma.type.v2.DocumentTypeList;
import juntadeandalucia.cice.pfirma.type.v2.Job;
import juntadeandalucia.cice.pfirma.type.v2.User;
import juntadeandalucia.cice.pfirma.type.v2.UserEmail;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdminService", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:v2.0")
@XmlSeeAlso({
    juntadeandalucia.cice.pfirma.admin.request.v2.ObjectFactory.class,
    juntadeandalucia.cice.pfirma.type.v2.ObjectFactory.class
})
public interface AdminService {


    /**
     * 
     * @param documentTypeList
     * @param applicationId
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "insertDocumentsType", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertDocumentsType")
    @ResponseWrapper(localName = "insertDocumentsTypeResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertDocumentsTypeResponse")
    public void insertDocumentsType(
        @WebParam(name = "applicationId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> applicationId,
        @WebParam(name = "documentTypeList", targetNamespace = "")
        DocumentTypeList documentTypeList)
        throws PfirmaException
    ;

    /**
     * 
     * @param documentTypeList
     * @param applicationId
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDocumentsType", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteDocumentsType")
    @ResponseWrapper(localName = "deleteDocumentsTypeResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteDocumentsTypeResponse")
    public void deleteDocumentsType(
        @WebParam(name = "applicationId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> applicationId,
        @WebParam(name = "documentTypeList", targetNamespace = "")
        DocumentTypeList documentTypeList)
        throws PfirmaException
    ;

    /**
     * 
     * @param documentTypeList
     * @param applicationId
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "updateDocumentsType", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateDocumentsType")
    @ResponseWrapper(localName = "updateDocumentsTypeResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateDocumentsTypeResponse")
    public void updateDocumentsType(
        @WebParam(name = "applicationId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> applicationId,
        @WebParam(name = "documentTypeList", targetNamespace = "")
        DocumentTypeList documentTypeList)
        throws PfirmaException
    ;

    /**
     * 
     * @param applicationId
     * @param user
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "insertUser", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertUser")
    @ResponseWrapper(localName = "insertUserResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertUserResponse")
    public void insertUser(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<User> user)
        throws PfirmaException
    ;

    /**
     * 
     * @param applicationId
     * @param user
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateUserResponse")
    public void updateUser(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<User> user)
        throws PfirmaException
    ;

    /**
     * 
     * @param applicationId
     * @param user
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteUserResponse")
    public void deleteUser(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<User> user)
        throws PfirmaException
    ;

    /**
     * 
     * @param applicationId
     * @param job
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "insertJob", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertJob")
    @ResponseWrapper(localName = "insertJobResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertJobResponse")
    public void insertJob(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "job", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Job> job)
        throws PfirmaException
    ;

    /**
     * 
     * @param applicationId
     * @param job
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "updateJob", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateJob")
    @ResponseWrapper(localName = "updateJobResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateJobResponse")
    public void updateJob(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "job", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Job> job)
        throws PfirmaException
    ;

    /**
     * 
     * @param applicationId
     * @param job
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteJob", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteJob")
    @ResponseWrapper(localName = "deleteJobResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteJobResponse")
    public void deleteJob(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "job", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Job> job)
        throws PfirmaException
    ;

    /**
     * 
     * @param userEmail
     * @param applicationId
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "insertUserEmail", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertUserEmail")
    @ResponseWrapper(localName = "insertUserEmailResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertUserEmailResponse")
    public void insertUserEmail(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "userEmail", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<UserEmail> userEmail)
        throws PfirmaException
    ;

    /**
     * 
     * @param userEmail
     * @param applicationId
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "updateUserEmail", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateUserEmail")
    @ResponseWrapper(localName = "updateUserEmailResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateUserEmailResponse")
    public void updateUserEmail(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "userEmail", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<UserEmail> userEmail)
        throws PfirmaException
    ;

    /**
     * 
     * @param userEmail
     * @param applicationId
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUserEmail", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteUserEmail")
    @ResponseWrapper(localName = "deleteUserEmailResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteUserEmailResponse")
    public void deleteUserEmail(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "userEmail", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<UserEmail> userEmail)
        throws PfirmaException
    ;

    /**
     * 
     * @param profile
     * @param applicationId
     * @param user
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "insertUserProfile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertUserProfile")
    @ResponseWrapper(localName = "insertUserProfileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertUserProfileResponse")
    public void insertUserProfile(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "profile", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> profile)
        throws PfirmaException
    ;

    /**
     * 
     * @param profiles
     * @param applicationId
     * @param user
     * @return
     *     returns java.lang.String
     * @throws PfirmaException
     */
    @WebMethod
    @WebResult(name = "profiles", targetNamespace = "")
    @RequestWrapper(localName = "insertManyUserProfile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertManyUserProfile")
    @ResponseWrapper(localName = "insertManyUserProfileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertManyUserProfileResponse")
    public String insertManyUserProfile(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "profiles", targetNamespace = "")
        List<String> profiles)
        throws PfirmaException
    ;

    /**
     * 
     * @param oldProfile
     * @param newProfile
     * @param applicationId
     * @param user
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "updateUserProfile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateUserProfile")
    @ResponseWrapper(localName = "updateUserProfileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateUserProfileResponse")
    public void updateUserProfile(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "oldProfile", targetNamespace = "")
        String oldProfile,
        @WebParam(name = "newProfile", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> newProfile)
        throws PfirmaException
    ;

    /**
     * 
     * @param profile
     * @param applicationId
     * @param user
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUserProfile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteUserProfile")
    @ResponseWrapper(localName = "deleteUserProfileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteUserProfileResponse")
    public void deleteUserProfile(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "profile", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> profile)
        throws PfirmaException
    ;

    /**
     * 
     * @param profiles
     * @param applicationId
     * @param user
     * @return
     *     returns java.lang.String
     * @throws PfirmaException
     */
    @WebMethod
    @WebResult(name = "profiles", targetNamespace = "")
    @RequestWrapper(localName = "deleteManyUserProfile", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteManyUserProfile")
    @ResponseWrapper(localName = "deleteManyUserProfileResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteManyUserProfileResponse")
    public String deleteManyUserProfile(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "profiles", targetNamespace = "")
        List<String> profiles)
        throws PfirmaException
    ;

    /**
     * 
     * @param main
     * @param applicationId
     * @param job
     * @param user
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "insertUserJob", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertUserJob")
    @ResponseWrapper(localName = "insertUserJobResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertUserJobResponse")
    public void insertUserJob(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "job", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Job> job,
        @WebParam(name = "main", targetNamespace = "")
        String main)
        throws PfirmaException
    ;

    /**
     * 
     * @param main
     * @param applicationId
     * @param job
     * @param user
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "updateUserJob", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateUserJob")
    @ResponseWrapper(localName = "updateUserJobResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateUserJobResponse")
    public void updateUserJob(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "job", targetNamespace = "")
        Job job,
        @WebParam(name = "main", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> main)
        throws PfirmaException
    ;

    /**
     * 
     * @param applicationId
     * @param job
     * @param user
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUserJob", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteUserJob")
    @ResponseWrapper(localName = "deleteUserJobResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteUserJobResponse")
    public void deleteUserJob(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "job", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Job> job)
        throws PfirmaException
    ;

    /**
     * 
     * @param ldap
     * @param applicationId
     * @param user
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "insertUserLDAP", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertUserLDAP")
    @ResponseWrapper(localName = "insertUserLDAPResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.InsertUserLDAPResponse")
    public void insertUserLDAP(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "ldap", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> ldap)
        throws PfirmaException
    ;

    /**
     * 
     * @param ldap
     * @param applicationId
     * @param user
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "updateUserLDAP", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateUserLDAP")
    @ResponseWrapper(localName = "updateUserLDAPResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateUserLDAPResponse")
    public void updateUserLDAP(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "ldap", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> ldap)
        throws PfirmaException
    ;

    /**
     * 
     * @param applicationId
     * @param user
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUserLDAP", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteUserLDAP")
    @ResponseWrapper(localName = "deleteUserLDAPResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.DeleteUserLDAPResponse")
    public void deleteUserLDAP(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<User> user)
        throws PfirmaException
    ;

    /**
     * 
     * @param valid
     * @param applicationId
     * @param user
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "updateUserValid", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateUserValid")
    @ResponseWrapper(localName = "updateUserValidResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:admin:request:v2.0", className = "juntadeandalucia.cice.pfirma.admin.request.v2.UpdateUserValidResponse")
    public void updateUserValid(
        @WebParam(name = "applicationId", targetNamespace = "")
        String applicationId,
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "valid", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> valid)
        throws PfirmaException
    ;

}
