
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ZPeEmpleadoDiplomaEvento.Exception", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class ZPeEmpleadoDiplomaEventoException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ZPeEmpleadoDiplomaEventoRfcException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ZPeEmpleadoDiplomaEventoException(String message, ZPeEmpleadoDiplomaEventoRfcException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ZPeEmpleadoDiplomaEventoException(String message, ZPeEmpleadoDiplomaEventoRfcException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoDiplomaEventoRfcException
     */
    public ZPeEmpleadoDiplomaEventoRfcException getFaultInfo() {
        return faultInfo;
    }

}
