
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_EMPLEADO_HIST_TITULACI", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSPEEMPLEADOHISTTITULACI {


    /**
     * 
     * @param tHistTitulacion
     * @param tNiveles
     * @param pernr
     * @param tTitulos
     */
    @WebMethod(operationName = "ZPeEmpleadoHistTitulacion", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_EMPLEADO_HIST_TITULACI:ZPeEmpleadoHistTitulacionRequest")
    @RequestWrapper(localName = "ZPeEmpleadoHistTitulacion", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoHistTitulacion")
    @ResponseWrapper(localName = "ZPeEmpleadoHistTitulacionResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoHistTitulacionResponse")
    public void zPeEmpleadoHistTitulacion(
        @WebParam(name = "Pernr", targetNamespace = "")
        String pernr,
        @WebParam(name = "THistTitulacion", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEmpleadoHistTitulacio> tHistTitulacion,
        @WebParam(name = "TNiveles", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEmpleadoHistTitulNiv> tNiveles,
        @WebParam(name = "TTitulos", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEmpleadoHistTitulTit> tTitulos);

}
