
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_EMPLEADO_jornada_diari", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:META-INF/wsdl/z_ws_pe_empleado_jornada_diari.wsdl")
public class ZWSPEEMPLEADOJORNADADIARI_Service
    extends Service
{

    private final static URL ZWSPEEMPLEADOJORNADADIARI_WSDL_LOCATION;
    private final static WebServiceException ZWSPEEMPLEADOJORNADADIARI_EXCEPTION;
    private final static QName ZWSPEEMPLEADOJORNADADIARI_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_JORNADA_DIARI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/z_ws_pe_empleado_jornada_diari.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }

        ZWSPEEMPLEADOJORNADADIARI_WSDL_LOCATION = url;
        ZWSPEEMPLEADOJORNADADIARI_EXCEPTION = e;
    }

    public ZWSPEEMPLEADOJORNADADIARI_Service() {
        super(__getWsdlLocation(), ZWSPEEMPLEADOJORNADADIARI_QNAME);
    }

    public ZWSPEEMPLEADOJORNADADIARI_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEEMPLEADOJORNADADIARI_QNAME, features);
    }

    public ZWSPEEMPLEADOJORNADADIARI_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEEMPLEADOJORNADADIARI_QNAME);
    }

    public ZWSPEEMPLEADOJORNADADIARI_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEEMPLEADOJORNADADIARI_QNAME, features);
    }

    public ZWSPEEMPLEADOJORNADADIARI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEEMPLEADOJORNADADIARI_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEEMPLEADOJORNADADIARI
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_jornada_diari")
    public ZWSPEEMPLEADOJORNADADIARI getZWSPEEMPLEADOJORNADADIARI() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_jornada_diari"), ZWSPEEMPLEADOJORNADADIARI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEEMPLEADOJORNADADIARI
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_jornada_diari")
    public ZWSPEEMPLEADOJORNADADIARI getZWSPEEMPLEADOJORNADADIARI(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_jornada_diari"), ZWSPEEMPLEADOJORNADADIARI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEEMPLEADOJORNADADIARI_EXCEPTION!= null) {
            throw ZWSPEEMPLEADOJORNADADIARI_EXCEPTION;
        }
        return ZWSPEEMPLEADOJORNADADIARI_WSDL_LOCATION;
    }

}
