
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_PROCESOS_SELECCION_INS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:META-INF/wsdl/z_ws_pe_procesos_seleccion_ins.wsdl")
public class ZWSPEPROCESOSSELECCIONINS_Service
    extends Service
{

    private final static URL ZWSPEPROCESOSSELECCIONINS_WSDL_LOCATION;
    private final static WebServiceException ZWSPEPROCESOSSELECCIONINS_EXCEPTION;
    private final static QName ZWSPEPROCESOSSELECCIONINS_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_PROCESOS_SELECCION_INS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/z_ws_pe_procesos_seleccion_ins.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEPROCESOSSELECCIONINS_WSDL_LOCATION = url;
        ZWSPEPROCESOSSELECCIONINS_EXCEPTION = e;
    }

    public ZWSPEPROCESOSSELECCIONINS_Service() {
        super(__getWsdlLocation(), ZWSPEPROCESOSSELECCIONINS_QNAME);
    }

    public ZWSPEPROCESOSSELECCIONINS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEPROCESOSSELECCIONINS_QNAME, features);
    }

    public ZWSPEPROCESOSSELECCIONINS_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEPROCESOSSELECCIONINS_QNAME);
    }

    public ZWSPEPROCESOSSELECCIONINS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEPROCESOSSELECCIONINS_QNAME, features);
    }

    public ZWSPEPROCESOSSELECCIONINS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEPROCESOSSELECCIONINS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEPROCESOSSELECCIONINS
     */
    @WebEndpoint(name = "Z_WS_PE_PROCESOS_SELECCION_INS")
    public ZWSPEPROCESOSSELECCIONINS getZWSPEPROCESOSSELECCIONINS() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_PROCESOS_SELECCION_INS"), ZWSPEPROCESOSSELECCIONINS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEPROCESOSSELECCIONINS
     */
    @WebEndpoint(name = "Z_WS_PE_PROCESOS_SELECCION_INS")
    public ZWSPEPROCESOSSELECCIONINS getZWSPEPROCESOSSELECCIONINS(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_PROCESOS_SELECCION_INS"), ZWSPEPROCESOSSELECCIONINS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEPROCESOSSELECCIONINS_EXCEPTION!= null) {
            throw ZWSPEPROCESOSSELECCIONINS_EXCEPTION;
        }
        return ZWSPEPROCESOSSELECCIONINS_WSDL_LOCATION;
    }

}
