
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_EMPLEADO_PRESTAMOS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/C:/Dev/INTEMASESA/modules/custom/sap-integration-services/src/main/resources/META-INF/wsdl/z_ws_pe_empleado_prestamos.wsdl")
public class ZWSPEEMPLEADOPRESTAMOS_Service
    extends Service
{

    private final static URL ZWSPEEMPLEADOPRESTAMOS_WSDL_LOCATION;
    private final static WebServiceException ZWSPEEMPLEADOPRESTAMOS_EXCEPTION;
    private final static QName ZWSPEEMPLEADOPRESTAMOS_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_PRESTAMOS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/z_ws_pe_empleado_prestamos.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEEMPLEADOPRESTAMOS_WSDL_LOCATION = url;
        ZWSPEEMPLEADOPRESTAMOS_EXCEPTION = e;
    }

    public ZWSPEEMPLEADOPRESTAMOS_Service() {
        super(__getWsdlLocation(), ZWSPEEMPLEADOPRESTAMOS_QNAME);
    }

    public ZWSPEEMPLEADOPRESTAMOS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEEMPLEADOPRESTAMOS_QNAME, features);
    }

    public ZWSPEEMPLEADOPRESTAMOS_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEEMPLEADOPRESTAMOS_QNAME);
    }

    public ZWSPEEMPLEADOPRESTAMOS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEEMPLEADOPRESTAMOS_QNAME, features);
    }

    public ZWSPEEMPLEADOPRESTAMOS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEEMPLEADOPRESTAMOS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEEMPLEADOPRESTAMOS
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_PRESTAMOS")
    public ZWSPEEMPLEADOPRESTAMOS getZWSPEEMPLEADOPRESTAMOS() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_PRESTAMOS"), ZWSPEEMPLEADOPRESTAMOS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEEMPLEADOPRESTAMOS
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_PRESTAMOS")
    public ZWSPEEMPLEADOPRESTAMOS getZWSPEEMPLEADOPRESTAMOS(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_PRESTAMOS"), ZWSPEEMPLEADOPRESTAMOS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEEMPLEADOPRESTAMOS_EXCEPTION!= null) {
            throw ZWSPEEMPLEADOPRESTAMOS_EXCEPTION;
        }
        return ZWSPEEMPLEADOPRESTAMOS_WSDL_LOCATION;
    }

}
