
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_PROCESOS_SELECCION_LIS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:META-INF/wsdl/z_ws_pe_procesos_seleccion_lis.wsdl")
public class ZWSPEPROCESOSSELECCIONLIS_Service
    extends Service
{

    private final static URL ZWSPEPROCESOSSELECCIONLIS_WSDL_LOCATION;
    private final static WebServiceException ZWSPEPROCESOSSELECCIONLIS_EXCEPTION;
    private final static QName ZWSPEPROCESOSSELECCIONLIS_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_PROCESOS_SELECCION_LIS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/z_ws_pe_procesos_seleccion_lis.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEPROCESOSSELECCIONLIS_WSDL_LOCATION = url;
        ZWSPEPROCESOSSELECCIONLIS_EXCEPTION = e;
    }

    public ZWSPEPROCESOSSELECCIONLIS_Service() {
        super(__getWsdlLocation(), ZWSPEPROCESOSSELECCIONLIS_QNAME);
    }

    public ZWSPEPROCESOSSELECCIONLIS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEPROCESOSSELECCIONLIS_QNAME, features);
    }

    public ZWSPEPROCESOSSELECCIONLIS_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEPROCESOSSELECCIONLIS_QNAME);
    }

    public ZWSPEPROCESOSSELECCIONLIS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEPROCESOSSELECCIONLIS_QNAME, features);
    }

    public ZWSPEPROCESOSSELECCIONLIS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEPROCESOSSELECCIONLIS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEPROCESOSSELECCIONLIS
     */
    @WebEndpoint(name = "Z_WS_PE_PROCESOS_SELECCION_LIS")
    public ZWSPEPROCESOSSELECCIONLIS getZWSPEPROCESOSSELECCIONLIS() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_PROCESOS_SELECCION_LIS"), ZWSPEPROCESOSSELECCIONLIS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEPROCESOSSELECCIONLIS
     */
    @WebEndpoint(name = "Z_WS_PE_PROCESOS_SELECCION_LIS")
    public ZWSPEPROCESOSSELECCIONLIS getZWSPEPROCESOSSELECCIONLIS(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_PROCESOS_SELECCION_LIS"), ZWSPEPROCESOSSELECCIONLIS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEPROCESOSSELECCIONLIS_EXCEPTION!= null) {
            throw ZWSPEPROCESOSSELECCIONLIS_EXCEPTION;
        }
        return ZWSPEPROCESOSSELECCIONLIS_WSDL_LOCATION;
    }

}
