
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_EMPLEADO_HIST_FORMACIO", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:META-INF/wsdl/z_ws_pe_empleado_histform.wsdl")
public class ZWSPEEMPLEADOHISTFORMACIO_Service
    extends Service
{

    private final static URL ZWSPEEMPLEADOHISTFORMACIO_WSDL_LOCATION;
    private final static WebServiceException ZWSPEEMPLEADOHISTFORMACIO_EXCEPTION;
    private final static QName ZWSPEEMPLEADOHISTFORMACIO_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_FORMACIO");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/z_ws_pe_empleado_histform.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEEMPLEADOHISTFORMACIO_WSDL_LOCATION = url;
        ZWSPEEMPLEADOHISTFORMACIO_EXCEPTION = e;
    }

    public ZWSPEEMPLEADOHISTFORMACIO_Service() {
        super(__getWsdlLocation(), ZWSPEEMPLEADOHISTFORMACIO_QNAME);
    }

    public ZWSPEEMPLEADOHISTFORMACIO_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEEMPLEADOHISTFORMACIO_QNAME, features);
    }

    public ZWSPEEMPLEADOHISTFORMACIO_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEEMPLEADOHISTFORMACIO_QNAME);
    }

    public ZWSPEEMPLEADOHISTFORMACIO_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEEMPLEADOHISTFORMACIO_QNAME, features);
    }

    public ZWSPEEMPLEADOHISTFORMACIO_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEEMPLEADOHISTFORMACIO_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEEMPLEADOHISTFORMACIO
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_HIST_FORMACIO")
    public ZWSPEEMPLEADOHISTFORMACIO getZWSPEEMPLEADOHISTFORMACIO() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_FORMACIO"), ZWSPEEMPLEADOHISTFORMACIO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEEMPLEADOHISTFORMACIO
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_HIST_FORMACIO")
    public ZWSPEEMPLEADOHISTFORMACIO getZWSPEEMPLEADOHISTFORMACIO(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_FORMACIO"), ZWSPEEMPLEADOHISTFORMACIO.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEEMPLEADOHISTFORMACIO_EXCEPTION!= null) {
            throw ZWSPEEMPLEADOHISTFORMACIO_EXCEPTION;
        }
        return ZWSPEEMPLEADOHISTFORMACIO_WSDL_LOCATION;
    }

}
