
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_MARCAJES_HISTORICO_ACT", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/Users/stejeros/Developer/source/emasesa/INTEMASESA/modules/custom/sap-integration-services/src/main/resources/META-INF/wsdl/z_ws_pe_marcajes_historico_act.wsdl")
public class ZWSPEMARCAJESHISTORICOACT_Service
    extends Service
{

    private final static URL ZWSPEMARCAJESHISTORICOACT_WSDL_LOCATION;
    private final static WebServiceException ZWSPEMARCAJESHISTORICOACT_EXCEPTION;
    private final static QName ZWSPEMARCAJESHISTORICOACT_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_MARCAJES_HISTORICO_ACT");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/stejeros/Developer/source/emasesa/INTEMASESA/modules/custom/sap-integration-services/src/main/resources/META-INF/wsdl/z_ws_pe_marcajes_historico_act.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEMARCAJESHISTORICOACT_WSDL_LOCATION = url;
        ZWSPEMARCAJESHISTORICOACT_EXCEPTION = e;
    }

    public ZWSPEMARCAJESHISTORICOACT_Service() {
        super(__getWsdlLocation(), ZWSPEMARCAJESHISTORICOACT_QNAME);
    }

    public ZWSPEMARCAJESHISTORICOACT_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEMARCAJESHISTORICOACT_QNAME, features);
    }

    public ZWSPEMARCAJESHISTORICOACT_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEMARCAJESHISTORICOACT_QNAME);
    }

    public ZWSPEMARCAJESHISTORICOACT_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEMARCAJESHISTORICOACT_QNAME, features);
    }

    public ZWSPEMARCAJESHISTORICOACT_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEMARCAJESHISTORICOACT_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEMARCAJESHISTORICOACT
     */
    @WebEndpoint(name = "Z_WS_PE_MARCAJES_HISTORICO_ACT")
    public ZWSPEMARCAJESHISTORICOACT getZWSPEMARCAJESHISTORICOACT() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_MARCAJES_HISTORICO_ACT"), ZWSPEMARCAJESHISTORICOACT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEMARCAJESHISTORICOACT
     */
    @WebEndpoint(name = "Z_WS_PE_MARCAJES_HISTORICO_ACT")
    public ZWSPEMARCAJESHISTORICOACT getZWSPEMARCAJESHISTORICOACT(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_MARCAJES_HISTORICO_ACT"), ZWSPEMARCAJESHISTORICOACT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEMARCAJESHISTORICOACT_EXCEPTION!= null) {
            throw ZWSPEMARCAJESHISTORICOACT_EXCEPTION;
        }
        return ZWSPEMARCAJESHISTORICOACT_WSDL_LOCATION;
    }

}
