
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_MARCAJES_HISTORICO_ACT", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSPEMARCAJESHISTORICOACT {


    /**
     * 
     * @param fechaInicio
     * @param pernr
     * @param fechaFin
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.TableOfZpeStMarcajesHistoricoActu
     */
    @WebMethod(operationName = "ZPeMarcajesHistoricoActual", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_MARCAJES_HISTORICO_ACT:ZPeMarcajesHistoricoActualRequest")
    @WebResult(name = "TEmpleados", targetNamespace = "")
    @RequestWrapper(localName = "ZPeMarcajesHistoricoActual", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeMarcajesHistoricoActual")
    @ResponseWrapper(localName = "ZPeMarcajesHistoricoActualResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeMarcajesHistoricoActualResponse")
    public TableOfZpeStMarcajesHistoricoActu zPeMarcajesHistoricoActual(
        @WebParam(name = "FechaFin", targetNamespace = "")
        String fechaFin,
        @WebParam(name = "FechaInicio", targetNamespace = "")
        String fechaInicio,
        @WebParam(name = "Pernr", targetNamespace = "")
        String pernr);

}
