
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_CIERTOS_DATOS_ESTRUCTU", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/META-INF/wsdl/z_ws_pe_ciertos_datos_estructu.wsdl")
public class ZWSPECIERTOSDATOSESTRUCTU_Service
    extends Service
{

    private final static URL ZWSPECIERTOSDATOSESTRUCTU_WSDL_LOCATION;
    private final static WebServiceException ZWSPECIERTOSDATOSESTRUCTU_EXCEPTION;
    private final static QName ZWSPECIERTOSDATOSESTRUCTU_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_CIERTOS_DATOS_ESTRUCTU");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/META-INF/wsdl/z_ws_pe_ciertos_datos_estructu.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPECIERTOSDATOSESTRUCTU_WSDL_LOCATION = url;
        ZWSPECIERTOSDATOSESTRUCTU_EXCEPTION = e;
    }

    public ZWSPECIERTOSDATOSESTRUCTU_Service() {
        super(__getWsdlLocation(), ZWSPECIERTOSDATOSESTRUCTU_QNAME);
    }

    public ZWSPECIERTOSDATOSESTRUCTU_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPECIERTOSDATOSESTRUCTU_QNAME, features);
    }

    public ZWSPECIERTOSDATOSESTRUCTU_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPECIERTOSDATOSESTRUCTU_QNAME);
    }

    public ZWSPECIERTOSDATOSESTRUCTU_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPECIERTOSDATOSESTRUCTU_QNAME, features);
    }

    public ZWSPECIERTOSDATOSESTRUCTU_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPECIERTOSDATOSESTRUCTU_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPECIERTOSDATOSESTRUCTU
     */
    @WebEndpoint(name = "Z_WS_PE_CIERTOS_DATOS_ESTRUCTU")
    public ZWSPECIERTOSDATOSESTRUCTU getZWSPECIERTOSDATOSESTRUCTU() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_CIERTOS_DATOS_ESTRUCTU"), ZWSPECIERTOSDATOSESTRUCTU.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPECIERTOSDATOSESTRUCTU
     */
    @WebEndpoint(name = "Z_WS_PE_CIERTOS_DATOS_ESTRUCTU")
    public ZWSPECIERTOSDATOSESTRUCTU getZWSPECIERTOSDATOSESTRUCTU(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_CIERTOS_DATOS_ESTRUCTU"), ZWSPECIERTOSDATOSESTRUCTU.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPECIERTOSDATOSESTRUCTU_EXCEPTION!= null) {
            throw ZWSPECIERTOSDATOSESTRUCTU_EXCEPTION;
        }
        return ZWSPECIERTOSDATOSESTRUCTU_WSDL_LOCATION;
    }

}
