
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_AYUDA_ESCOLAR", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/Users/stejeros/Developer/source/emasesa/INTEMASESA/modules/custom/sap-integration-services/src/main/resources/META-INF/wsdl/z_ws_pe_ayuda_escolar.wsdl")
public class ZWSPEAYUDAESCOLAR_Service
    extends Service
{

    private final static URL ZWSPEAYUDAESCOLAR_WSDL_LOCATION;
    private final static WebServiceException ZWSPEAYUDAESCOLAR_EXCEPTION;
    private final static QName ZWSPEAYUDAESCOLAR_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_AYUDA_ESCOLAR");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/stejeros/Developer/source/emasesa/INTEMASESA/modules/custom/sap-integration-services/src/main/resources/META-INF/wsdl/z_ws_pe_ayuda_escolar.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEAYUDAESCOLAR_WSDL_LOCATION = url;
        ZWSPEAYUDAESCOLAR_EXCEPTION = e;
    }

    public ZWSPEAYUDAESCOLAR_Service() {
        super(__getWsdlLocation(), ZWSPEAYUDAESCOLAR_QNAME);
    }

    public ZWSPEAYUDAESCOLAR_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEAYUDAESCOLAR_QNAME, features);
    }

    public ZWSPEAYUDAESCOLAR_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEAYUDAESCOLAR_QNAME);
    }

    public ZWSPEAYUDAESCOLAR_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEAYUDAESCOLAR_QNAME, features);
    }

    public ZWSPEAYUDAESCOLAR_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEAYUDAESCOLAR_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEAYUDAESCOLAR
     */
    @WebEndpoint(name = "Z_WS_PE_AYUDA_ESCOLAR")
    public ZWSPEAYUDAESCOLAR getZWSPEAYUDAESCOLAR() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_AYUDA_ESCOLAR"), ZWSPEAYUDAESCOLAR.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEAYUDAESCOLAR
     */
    @WebEndpoint(name = "Z_WS_PE_AYUDA_ESCOLAR")
    public ZWSPEAYUDAESCOLAR getZWSPEAYUDAESCOLAR(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_AYUDA_ESCOLAR"), ZWSPEAYUDAESCOLAR.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEAYUDAESCOLAR_EXCEPTION!= null) {
            throw ZWSPEAYUDAESCOLAR_EXCEPTION;
        }
        return ZWSPEAYUDAESCOLAR_WSDL_LOCATION;
    }

}
