
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_EMPLEADO_HIST_INNOVACI", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSPEEMPLEADOHISTINNOVACI {


    /**
     * 
     * @param pernr
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.TableOfZpeStEmpleadoHistInnovacio
     */
    @WebMethod(operationName = "ZPeEmpleadoHistInnovacion", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_EMPLEADO_HIST_INNOVACI:ZPeEmpleadoHistInnovacionRequest")
    @WebResult(name = "THistInnovacion", targetNamespace = "")
    @RequestWrapper(localName = "ZPeEmpleadoHistInnovacion", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoHistInnovacion")
    @ResponseWrapper(localName = "ZPeEmpleadoHistInnovacionResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoHistInnovacionResponse")
    public TableOfZpeStEmpleadoHistInnovacio zPeEmpleadoHistInnovacion(
        @WebParam(name = "Pernr", targetNamespace = "")
        String pernr);

}
