
package com.sap.document.sap.soap.functions.mc_style;

import com.sap.document.sap.rfc.functions.ZPESTINSAYUDAESCOLAR;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_AYUDA_ESCOLAR", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    com.sap.document.sap.rfc.functions.ObjectFactory.class,
    com.sap.document.sap.soap.functions.mc_style.ObjectFactory.class
})
public interface ZWSPEAYUDAESCOLAR {


    /**
     * 
     * @param tAyudasSolicitadas
     * @param tInsAyudaEscolar
     * @param pernr
     * @param tBeneficiarios
     * @param tEstudios
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.Bapireturn1
     */
    @WebMethod(operationName = "ZPeAyudaEscolar", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_AYUDA_ESCOLAR:ZPeAyudaEscolarRequest")
    @WebResult(name = "Return", targetNamespace = "")
    @RequestWrapper(localName = "ZPeAyudaEscolar", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeAyudaEscolar")
    @ResponseWrapper(localName = "ZPeAyudaEscolarResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeAyudaEscolarResponse")
    public Bapireturn1 zPeAyudaEscolar(
        @WebParam(name = "Pernr", targetNamespace = "")
        String pernr,
        @WebParam(name = "TInsAyudaEscolar", targetNamespace = "")
        ZPESTINSAYUDAESCOLAR tInsAyudaEscolar,
        @WebParam(name = "TAyudasSolicitadas", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStAyudasSolicitadas> tAyudasSolicitadas,
        @WebParam(name = "TBeneficiarios", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStBeneficiarios> tBeneficiarios,
        @WebParam(name = "TEstudios", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEstudios> tEstudios);

}
