
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_EMPLEADO_RELAC_LABORAL", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:META-INF/wsdl/z_ws_pe_empleado_relac_laboral.wsdl")
public class ZWSPEEMPLEADORELACLABORAL_Service
    extends Service
{

    private final static URL ZWSPEEMPLEADORELACLABORAL_WSDL_LOCATION;
    private final static WebServiceException ZWSPEEMPLEADORELACLABORAL_EXCEPTION;
    private final static QName ZWSPEEMPLEADORELACLABORAL_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_RELAC_LABORAL");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/z_ws_pe_empleado_relac_laboral.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEEMPLEADORELACLABORAL_WSDL_LOCATION = url;
        ZWSPEEMPLEADORELACLABORAL_EXCEPTION = e;
    }

    public ZWSPEEMPLEADORELACLABORAL_Service() {
        super(__getWsdlLocation(), ZWSPEEMPLEADORELACLABORAL_QNAME);
    }

    public ZWSPEEMPLEADORELACLABORAL_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEEMPLEADORELACLABORAL_QNAME, features);
    }

    public ZWSPEEMPLEADORELACLABORAL_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEEMPLEADORELACLABORAL_QNAME);
    }

    public ZWSPEEMPLEADORELACLABORAL_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEEMPLEADORELACLABORAL_QNAME, features);
    }

    public ZWSPEEMPLEADORELACLABORAL_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEEMPLEADORELACLABORAL_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEEMPLEADORELACLABORAL
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_RELAC_LABORAL")
    public ZWSPEEMPLEADORELACLABORAL getZWSPEEMPLEADORELACLABORAL() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_RELAC_LABORAL"), ZWSPEEMPLEADORELACLABORAL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEEMPLEADORELACLABORAL
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_RELAC_LABORAL")
    public ZWSPEEMPLEADORELACLABORAL getZWSPEEMPLEADORELACLABORAL(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_RELAC_LABORAL"), ZWSPEEMPLEADORELACLABORAL.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEEMPLEADORELACLABORAL_EXCEPTION!= null) {
            throw ZWSPEEMPLEADORELACLABORAL_EXCEPTION;
        }
        return ZWSPEEMPLEADORELACLABORAL_WSDL_LOCATION;
    }

}
