
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_CENTROS_DISTANCIAS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:META-INF/wsdl/z_ws_pe_centros_distancias.wsdl")
public class ZWSPECENTROSDISTANCIAS_Service
    extends Service
{

    private final static URL ZWSPECENTROSDISTANCIAS_WSDL_LOCATION;
    private final static WebServiceException ZWSPECENTROSDISTANCIAS_EXCEPTION;
    private final static QName ZWSPECENTROSDISTANCIAS_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_CENTROS_DISTANCIAS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/z_ws_pe_centros_distancias.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPECENTROSDISTANCIAS_WSDL_LOCATION = url;
        ZWSPECENTROSDISTANCIAS_EXCEPTION = e;
    }

    public ZWSPECENTROSDISTANCIAS_Service() {
        super(__getWsdlLocation(), ZWSPECENTROSDISTANCIAS_QNAME);
    }

    public ZWSPECENTROSDISTANCIAS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPECENTROSDISTANCIAS_QNAME, features);
    }

    public ZWSPECENTROSDISTANCIAS_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPECENTROSDISTANCIAS_QNAME);
    }

    public ZWSPECENTROSDISTANCIAS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPECENTROSDISTANCIAS_QNAME, features);
    }

    public ZWSPECENTROSDISTANCIAS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPECENTROSDISTANCIAS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Z_WS_PE_CENTROS_DISTANCIAS
     */
    @WebEndpoint(name = "Z_WS_PE_CENTROS_DISTANCIAS")
    public ZWSPECENTROSDISTANCIAS getZWSPECENTROSDISTANCIASF() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_CENTROS_DISTANCIAS"), ZWSPECENTROSDISTANCIAS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPECONSULTACERTRETPDF
     */
    @WebEndpoint(name = "Z_WS_PE_CENTROS_DISTANCIAS")
    public ZWSPECENTROSDISTANCIAS getZWSPECENTROSDISTANCIAS(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_CENTROS_DISTANCIAS"), ZWSPECENTROSDISTANCIAS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPECENTROSDISTANCIAS_EXCEPTION!= null) {
            throw ZWSPECENTROSDISTANCIAS_EXCEPTION;
        }
        return ZWSPECENTROSDISTANCIAS_WSDL_LOCATION;
    }

}
