
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_ACT_DATOS_PERSONALES", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSPEACTDATOSPERSONALES {


    /**
     * 
     * @param tEmpleados
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.Bapireturn1
     */
    @WebMethod(operationName = "ZPeActDatosPersonales", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_ACT_DATOS_PERSONALES:ZPeActDatosPersonalesRequest")
    @WebResult(name = "Return", targetNamespace = "")
    @RequestWrapper(localName = "ZPeActDatosPersonales", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeActDatosPersonales")
    @ResponseWrapper(localName = "ZPeActDatosPersonalesResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeActDatosPersonalesResponse")
    public Bapireturn1 zPeActDatosPersonales(
        @WebParam(name = "TEmpleados", targetNamespace = "")
        ZpeStActDatosPersonales tEmpleados);

}
