
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_DETECNECFORM", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:META-INF/wsdl/z_ws_pe_detecnecform.wsdl")
public class ZWSPEDETECNECFORM_Service
    extends Service
{

    private final static URL ZWSPEDETECNECFORM_WSDL_LOCATION;
    private final static WebServiceException ZWSPEDETECNECFORM_EXCEPTION;
    private final static QName ZWSPEDETECNECFORM_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_DETECNECFORM");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/z_ws_pe_detecnecform.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEDETECNECFORM_WSDL_LOCATION = url;
        ZWSPEDETECNECFORM_EXCEPTION = e;
    }

    public ZWSPEDETECNECFORM_Service() {
        super(__getWsdlLocation(), ZWSPEDETECNECFORM_QNAME);
    }

    public ZWSPEDETECNECFORM_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEDETECNECFORM_QNAME, features);
    }

    public ZWSPEDETECNECFORM_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEDETECNECFORM_QNAME);
    }

    public ZWSPEDETECNECFORM_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEDETECNECFORM_QNAME, features);
    }

    public ZWSPEDETECNECFORM_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEDETECNECFORM_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEDETECNECFORM
     */
    @WebEndpoint(name = "Z_WS_PE_DETECNECFORM")
    public ZWSPEDETECNECFORM getZWSPEDETECNECFORM() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_DETECNECFORM"), ZWSPEDETECNECFORM.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEDETECNECFORM
     */
    @WebEndpoint(name = "Z_WS_PE_DETECNECFORM")
    public ZWSPEDETECNECFORM getZWSPEDETECNECFORM(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_DETECNECFORM"), ZWSPEDETECNECFORM.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEDETECNECFORM_EXCEPTION!= null) {
            throw ZWSPEDETECNECFORM_EXCEPTION;
        }
        return ZWSPEDETECNECFORM_WSDL_LOCATION;
    }

}
