
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_EMPLEADO_HIST_CONTR_CA", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:META-INF/wsdl/z_ws_pe_empleado_hist_contr_ca.wsdl")
public class ZWSPEEMPLEADOHISTCONTRCA_Service
    extends Service
{

    private final static URL ZWSPEEMPLEADOHISTCONTRCA_WSDL_LOCATION;
    private final static WebServiceException ZWSPEEMPLEADOHISTCONTRCA_EXCEPTION;
    private final static QName ZWSPEEMPLEADOHISTCONTRCA_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_CONTR_CA");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/z_ws_pe_empleado_hist_contr_ca.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEEMPLEADOHISTCONTRCA_WSDL_LOCATION = url;
        ZWSPEEMPLEADOHISTCONTRCA_EXCEPTION = e;
    }

    public ZWSPEEMPLEADOHISTCONTRCA_Service() {
        super(__getWsdlLocation(), ZWSPEEMPLEADOHISTCONTRCA_QNAME);
    }

    public ZWSPEEMPLEADOHISTCONTRCA_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEEMPLEADOHISTCONTRCA_QNAME, features);
    }

    public ZWSPEEMPLEADOHISTCONTRCA_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEEMPLEADOHISTCONTRCA_QNAME);
    }

    public ZWSPEEMPLEADOHISTCONTRCA_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEEMPLEADOHISTCONTRCA_QNAME, features);
    }

    public ZWSPEEMPLEADOHISTCONTRCA_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEEMPLEADOHISTCONTRCA_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEEMPLEADOHISTCONTRCA
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_HIST_CONTR_CA")
    public ZWSPEEMPLEADOHISTCONTRCA getZWSPEEMPLEADOHISTCONTRCA() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_CONTR_CA"), ZWSPEEMPLEADOHISTCONTRCA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEEMPLEADOHISTCONTRCA
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_HIST_CONTR_CA")
    public ZWSPEEMPLEADOHISTCONTRCA getZWSPEEMPLEADOHISTCONTRCA(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_CONTR_CA"), ZWSPEEMPLEADOHISTCONTRCA.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEEMPLEADOHISTCONTRCA_EXCEPTION!= null) {
            throw ZWSPEEMPLEADOHISTCONTRCA_EXCEPTION;
        }
        return ZWSPEEMPLEADOHISTCONTRCA_WSDL_LOCATION;
    }

}
