
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_EMPLEADO_HIST_PERCONDU", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/C:/Dev/INTEMASESA/modules/custom/sap-integration-services/src/main/resources/META-INF/wsdl/z_ws_pe_empleado_hist_percondu.wsdl")
public class ZWSPEEMPLEADOHISTPERCONDU_Service
    extends Service
{

    private final static URL ZWSPEEMPLEADOHISTPERCONDU_WSDL_LOCATION;
    private final static WebServiceException ZWSPEEMPLEADOHISTPERCONDU_EXCEPTION;
    private final static QName ZWSPEEMPLEADOHISTPERCONDU_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_PERCONDU");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Dev/INTEMASESA/modules/custom/sap-integration-services/src/main/resources/META-INF/wsdl/z_ws_pe_empleado_hist_percondu.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEEMPLEADOHISTPERCONDU_WSDL_LOCATION = url;
        ZWSPEEMPLEADOHISTPERCONDU_EXCEPTION = e;
    }

    public ZWSPEEMPLEADOHISTPERCONDU_Service() {
        super(__getWsdlLocation(), ZWSPEEMPLEADOHISTPERCONDU_QNAME);
    }

    public ZWSPEEMPLEADOHISTPERCONDU_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEEMPLEADOHISTPERCONDU_QNAME, features);
    }

    public ZWSPEEMPLEADOHISTPERCONDU_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEEMPLEADOHISTPERCONDU_QNAME);
    }

    public ZWSPEEMPLEADOHISTPERCONDU_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEEMPLEADOHISTPERCONDU_QNAME, features);
    }

    public ZWSPEEMPLEADOHISTPERCONDU_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEEMPLEADOHISTPERCONDU_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEEMPLEADOHISTPERCONDU
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_HIST_PERCONDU")
    public ZWSPEEMPLEADOHISTPERCONDU getZWSPEEMPLEADOHISTPERCONDU() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_PERCONDU"), ZWSPEEMPLEADOHISTPERCONDU.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEEMPLEADOHISTPERCONDU
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_HIST_PERCONDU")
    public ZWSPEEMPLEADOHISTPERCONDU getZWSPEEMPLEADOHISTPERCONDU(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_PERCONDU"), ZWSPEEMPLEADOHISTPERCONDU.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEEMPLEADOHISTPERCONDU_EXCEPTION!= null) {
            throw ZWSPEEMPLEADOHISTPERCONDU_EXCEPTION;
        }
        return ZWSPEEMPLEADOHISTPERCONDU_WSDL_LOCATION;
    }

}
