
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_EMPLEADO_BANCO", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:META-INF/wsdl/z_ws_pe_empleado_banco.wsdl")
public class ZWSPEEMPLEADOBANCO_Service
    extends Service
{

    private final static URL ZWSPEEMPLEADOBANCO_WSDL_LOCATION;
    private final static WebServiceException ZWSPEEMPLEADOBANCO_EXCEPTION;
    private final static QName ZWSPEEMPLEADOBANCO_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_BANCO");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/z_ws_pe_empleado_banco.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEEMPLEADOBANCO_WSDL_LOCATION = url;
        ZWSPEEMPLEADOBANCO_EXCEPTION = e;
    }

    public ZWSPEEMPLEADOBANCO_Service() {
        super(__getWsdlLocation(), ZWSPEEMPLEADOBANCO_QNAME);
    }

    public ZWSPEEMPLEADOBANCO_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEEMPLEADOBANCO_QNAME, features);
    }

    public ZWSPEEMPLEADOBANCO_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEEMPLEADOBANCO_QNAME);
    }

    public ZWSPEEMPLEADOBANCO_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEEMPLEADOBANCO_QNAME, features);
    }

    public ZWSPEEMPLEADOBANCO_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEEMPLEADOBANCO_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEEMPLEADOBANCO
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_BANCO")
    public ZWSPEEMPLEADOBANCO getZWSPEEMPLEADOBANCO() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_BANCO"), ZWSPEEMPLEADOBANCO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEEMPLEADOBANCO
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_BANCO")
    public ZWSPEEMPLEADOBANCO getZWSPEEMPLEADOBANCO(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_BANCO"), ZWSPEEMPLEADOBANCO.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEEMPLEADOBANCO_EXCEPTION!= null) {
            throw ZWSPEEMPLEADOBANCO_EXCEPTION;
        }
        return ZWSPEEMPLEADOBANCO_WSDL_LOCATION;
    }

}
