
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "z_ws_pe_centros_distancias", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSPECENTROSDISTANCIAS {


    /**
     * 
     * @param destino
     * @param origen
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.TableOfZpeStCentrosDistancias
     */
    @WebMethod(operationName = "ZPeCentrosDistancias", action = "urn:sap-com:document:sap:soap:functions:mc-style:z_ws_pe_centros_distancias:ZPeCentrosDistanciasRequest")
    @WebResult(name = "TCentrosDistancias", targetNamespace = "")
    @RequestWrapper(localName = "ZPeCentrosDistancias", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeCentrosDistancias")
    @ResponseWrapper(localName = "ZPeCentrosDistanciasResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeCentrosDistanciasResponse")
    public TableOfZpeStCentrosDistancias zPeCentrosDistancias(
        @WebParam(name = "Destino", targetNamespace = "")
        String destino,
        @WebParam(name = "Origen", targetNamespace = "")
        String origen);

}
