
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_EMPLEADO_HISTFORM", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSPEEMPLEADOHISTFORM {


    /**
     * 
     * @param tExterna
     * @param imPernr
     * @param tImpartida
     * @param tInterna
     */
    @WebMethod(operationName = "ZPeEmpleadoHistform", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_EMPLEADO_HISTFORM:ZPeEmpleadoHistformRequest")
    @RequestWrapper(localName = "ZPeEmpleadoHistform", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoHistform")
    @ResponseWrapper(localName = "ZPeEmpleadoHistformResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoHistformResponse")
    public void zPeEmpleadoHistform(
        @WebParam(name = "ImPernr", targetNamespace = "")
        String imPernr,
        @WebParam(name = "TExterna", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEmpleadoHistform> tExterna,
        @WebParam(name = "TImpartida", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEmpleadoHistform> tImpartida,
        @WebParam(name = "TInterna", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEmpleadoHistform> tInterna);

}
