
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_EMPLEADO_HIST_FORMACIO", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSPEEMPLEADOHISTFORMACIO {


    /**
     * 
     * @param eventoId
     * @param tExterna
     * @param tPaises
     * @param exReturn
     * @param pernr
     * @param exData
     * @param tImpartida
     * @param tInterna
     */
    @WebMethod(operationName = "ZPeEmpleadoHistFormacion", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_EMPLEADO_HIST_FORMACIO:ZPeEmpleadoHistFormacionRequest")
    @RequestWrapper(localName = "ZPeEmpleadoHistFormacion", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoHistFormacion")
    @ResponseWrapper(localName = "ZPeEmpleadoHistFormacionResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoHistFormacionResponse")
    public void zPeEmpleadoHistFormacion(
        @WebParam(name = "EventoId", targetNamespace = "")
        String eventoId,
        @WebParam(name = "Pernr", targetNamespace = "")
        String pernr,
        @WebParam(name = "ExData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<byte[]> exData,
        @WebParam(name = "ExReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> exReturn,
        @WebParam(name = "TExterna", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEmpleadoHistFormacion> tExterna,
        @WebParam(name = "TImpartida", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEmpleadoHistFormacion> tImpartida,
        @WebParam(name = "TInterna", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEmpleadoHistFormacion> tInterna,
        @WebParam(name = "TPaises", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEmpleadoHistFormPais> tPaises);

}
