
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_EMPLEADO_HIST_INNOVACI", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:META-INF/wsdl/z_ws_pe_empleado_hist_innovaci.wsdl")
public class ZWSPEEMPLEADOHISTINNOVACI_Service
    extends Service
{

    private final static URL ZWSPEEMPLEADOHISTINNOVACI_WSDL_LOCATION;
    private final static WebServiceException ZWSPEEMPLEADOHISTINNOVACI_EXCEPTION;
    private final static QName ZWSPEEMPLEADOHISTINNOVACI_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_INNOVACI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/z_ws_pe_empleado_hist_innovaci.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEEMPLEADOHISTINNOVACI_WSDL_LOCATION = url;
        ZWSPEEMPLEADOHISTINNOVACI_EXCEPTION = e;
    }

    public ZWSPEEMPLEADOHISTINNOVACI_Service() {
        super(__getWsdlLocation(), ZWSPEEMPLEADOHISTINNOVACI_QNAME);
    }

    public ZWSPEEMPLEADOHISTINNOVACI_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEEMPLEADOHISTINNOVACI_QNAME, features);
    }

    public ZWSPEEMPLEADOHISTINNOVACI_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEEMPLEADOHISTINNOVACI_QNAME);
    }

    public ZWSPEEMPLEADOHISTINNOVACI_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEEMPLEADOHISTINNOVACI_QNAME, features);
    }

    public ZWSPEEMPLEADOHISTINNOVACI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEEMPLEADOHISTINNOVACI_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEEMPLEADOHISTINNOVACI
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_HIST_INNOVACI")
    public ZWSPEEMPLEADOHISTINNOVACI getZWSPEEMPLEADOHISTINNOVACI() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_INNOVACI"), ZWSPEEMPLEADOHISTINNOVACI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEEMPLEADOHISTINNOVACI
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_HIST_INNOVACI")
    public ZWSPEEMPLEADOHISTINNOVACI getZWSPEEMPLEADOHISTINNOVACI(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_INNOVACI"), ZWSPEEMPLEADOHISTINNOVACI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEEMPLEADOHISTINNOVACI_EXCEPTION!= null) {
            throw ZWSPEEMPLEADOHISTINNOVACI_EXCEPTION;
        }
        return ZWSPEEMPLEADOHISTINNOVACI_WSDL_LOCATION;
    }

}
