
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_EMPLEADO_HIST_PERCONDU", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSPEEMPLEADOHISTPERCONDU {


    /**
     * 
     * @param tPermisosConducir
     * @param tHistPermisosConducir
     * @param pernr
     */
    @WebMethod(operationName = "ZPeEmpleadoHistPercondu", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_EMPLEADO_HIST_PERCONDU:ZPeEmpleadoHistPerconduRequest")
    @RequestWrapper(localName = "ZPeEmpleadoHistPercondu", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoHistPercondu")
    @ResponseWrapper(localName = "ZPeEmpleadoHistPerconduResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoHistPerconduResponse")
    public void zPeEmpleadoHistPercondu(
        @WebParam(name = "Pernr", targetNamespace = "")
        String pernr,
        @WebParam(name = "THistPermisosConducir", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEmpleadoHistPercond> tHistPermisosConducir,
        @WebParam(name = "TPermisosConducir", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEmpleadoHistPercondL> tPermisosConducir);

}
