
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_PROCESOS_SELECCION_LIS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSPEPROCESOSSELECCIONLIS {


    /**
     * 
     * @param imTipo
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.TableOfZpeStProcesoSeleccionLista
     */
    @WebMethod(operationName = "ZPeProcesosSeleccionLista", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_PROCESOS_SELECCION_LIS:ZPeProcesosSeleccionListaRequest")
    @WebResult(name = "ToProcesos", targetNamespace = "")
    @RequestWrapper(localName = "ZPeProcesosSeleccionLista", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeProcesosSeleccionLista")
    @ResponseWrapper(localName = "ZPeProcesosSeleccionListaResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeProcesosSeleccionListaResponse")
    public TableOfZpeStProcesoSeleccionLista zPeProcesosSeleccionLista(
        @WebParam(name = "ImTipo", targetNamespace = "")
        String imTipo);

}
