
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_EMPLEADO_DIPLOMA_EVENT", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:META-INF/wsdl/z_ws_pe_empleado_diploma_event.wsdl")
public class ZWSPEEMPLEADODIPLOMAEVENT_Service
    extends Service
{

    private final static URL ZWSPEEMPLEADODIPLOMAEVENT_WSDL_LOCATION;
    private final static WebServiceException ZWSPEEMPLEADODIPLOMAEVENT_EXCEPTION;
    private final static QName ZWSPEEMPLEADODIPLOMAEVENT_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_DIPLOMA_EVENT");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/z_ws_pe_empleado_diploma_event.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEEMPLEADODIPLOMAEVENT_WSDL_LOCATION = url;
        ZWSPEEMPLEADODIPLOMAEVENT_EXCEPTION = e;
    }

    public ZWSPEEMPLEADODIPLOMAEVENT_Service() {
        super(__getWsdlLocation(), ZWSPEEMPLEADODIPLOMAEVENT_QNAME);
    }

    public ZWSPEEMPLEADODIPLOMAEVENT_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEEMPLEADODIPLOMAEVENT_QNAME, features);
    }

    public ZWSPEEMPLEADODIPLOMAEVENT_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEEMPLEADODIPLOMAEVENT_QNAME);
    }

    public ZWSPEEMPLEADODIPLOMAEVENT_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEEMPLEADODIPLOMAEVENT_QNAME, features);
    }

    public ZWSPEEMPLEADODIPLOMAEVENT_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEEMPLEADODIPLOMAEVENT_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEEMPLEADODIPLOMAEVENT
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_DIPLOMA_EVENT")
    public ZWSPEEMPLEADODIPLOMAEVENT getZWSPEEMPLEADODIPLOMAEVENT() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_DIPLOMA_EVENT"), ZWSPEEMPLEADODIPLOMAEVENT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEEMPLEADODIPLOMAEVENT
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_DIPLOMA_EVENT")
    public ZWSPEEMPLEADODIPLOMAEVENT getZWSPEEMPLEADODIPLOMAEVENT(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_DIPLOMA_EVENT"), ZWSPEEMPLEADODIPLOMAEVENT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEEMPLEADODIPLOMAEVENT_EXCEPTION!= null) {
            throw ZWSPEEMPLEADODIPLOMAEVENT_EXCEPTION;
        }
        return ZWSPEEMPLEADODIPLOMAEVENT_WSDL_LOCATION;
    }

}
