
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_EMPLEADO_DATOS_PERSONA", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/Users/stejeros/Developer/source/emasesa/INTEMASESA/modules/custom/sap-integration-services/src/main/resources/META-INF/wsdl/z_ws_pe_empleado_datos_persona.wsdl")
public class ZWSPEEMPLEADODATOSPERSONA_Service
    extends Service
{

    private final static URL ZWSPEEMPLEADODATOSPERSONA_WSDL_LOCATION;
    private final static WebServiceException ZWSPEEMPLEADODATOSPERSONA_EXCEPTION;
    private final static QName ZWSPEEMPLEADODATOSPERSONA_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_DATOS_PERSONA");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/stejeros/Developer/source/emasesa/INTEMASESA/modules/custom/sap-integration-services/src/main/resources/META-INF/wsdl/z_ws_pe_empleado_datos_persona.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEEMPLEADODATOSPERSONA_WSDL_LOCATION = url;
        ZWSPEEMPLEADODATOSPERSONA_EXCEPTION = e;
    }

    public ZWSPEEMPLEADODATOSPERSONA_Service() {
        super(__getWsdlLocation(), ZWSPEEMPLEADODATOSPERSONA_QNAME);
    }

    public ZWSPEEMPLEADODATOSPERSONA_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEEMPLEADODATOSPERSONA_QNAME, features);
    }

    public ZWSPEEMPLEADODATOSPERSONA_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEEMPLEADODATOSPERSONA_QNAME);
    }

    public ZWSPEEMPLEADODATOSPERSONA_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEEMPLEADODATOSPERSONA_QNAME, features);
    }

    public ZWSPEEMPLEADODATOSPERSONA_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEEMPLEADODATOSPERSONA_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEEMPLEADODATOSPERSONA
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_DATOS_PERSONA")
    public ZWSPEEMPLEADODATOSPERSONA getZWSPEEMPLEADODATOSPERSONA() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_DATOS_PERSONA"), ZWSPEEMPLEADODATOSPERSONA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEEMPLEADODATOSPERSONA
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_DATOS_PERSONA")
    public ZWSPEEMPLEADODATOSPERSONA getZWSPEEMPLEADODATOSPERSONA(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_DATOS_PERSONA"), ZWSPEEMPLEADODATOSPERSONA.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEEMPLEADODATOSPERSONA_EXCEPTION!= null) {
            throw ZWSPEEMPLEADODATOSPERSONA_EXCEPTION;
        }
        return ZWSPEEMPLEADODATOSPERSONA_WSDL_LOCATION;
    }

}
