
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_EMPLEADO_DOMICILIO", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:META-INF/wsdl/z_ws_pe_empleado_domicilio.wsdl")
public class ZWSPEEMPLEADODOMICILIO_Service
    extends Service
{

    private final static URL ZWSPEEMPLEADODOMICILIO_WSDL_LOCATION;
    private final static WebServiceException ZWSPEEMPLEADODOMICILIO_EXCEPTION;
    private final static QName ZWSPEEMPLEADODOMICILIO_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_DOMICILIO");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/z_ws_pe_empleado_domicilio.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEEMPLEADODOMICILIO_WSDL_LOCATION = url;
        ZWSPEEMPLEADODOMICILIO_EXCEPTION = e;
    }

    public ZWSPEEMPLEADODOMICILIO_Service() {
        super(__getWsdlLocation(), ZWSPEEMPLEADODOMICILIO_QNAME);
    }

    public ZWSPEEMPLEADODOMICILIO_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEEMPLEADODOMICILIO_QNAME, features);
    }

    public ZWSPEEMPLEADODOMICILIO_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEEMPLEADODOMICILIO_QNAME);
    }

    public ZWSPEEMPLEADODOMICILIO_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEEMPLEADODOMICILIO_QNAME, features);
    }

    public ZWSPEEMPLEADODOMICILIO_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEEMPLEADODOMICILIO_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEEMPLEADODOMICILIO
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_DOMICILIO")
    public ZWSPEEMPLEADODOMICILIO getZWSPEEMPLEADODOMICILIO() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_DOMICILIO"), ZWSPEEMPLEADODOMICILIO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEEMPLEADODOMICILIO
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_DOMICILIO")
    public ZWSPEEMPLEADODOMICILIO getZWSPEEMPLEADODOMICILIO(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_DOMICILIO"), ZWSPEEMPLEADODOMICILIO.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEEMPLEADODOMICILIO_EXCEPTION!= null) {
            throw ZWSPEEMPLEADODOMICILIO_EXCEPTION;
        }
        return ZWSPEEMPLEADODOMICILIO_WSDL_LOCATION;
    }

}
