
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_EMPLEADO_PRESTAMOS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSPEEMPLEADOPRESTAMOS {


    /**
     * 
     * @param pernr
     * @param fechaInicioVacaciones
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.TableOfZpeStEmpleadoPrestamos
     */
    @WebMethod(operationName = "ZPeEmpleadoPrestamos", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_EMPLEADO_PRESTAMOS:ZPeEmpleadoPrestamosRequest")
    @WebResult(name = "TEmpleados", targetNamespace = "")
    @RequestWrapper(localName = "ZPeEmpleadoPrestamos", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoPrestamos")
    @ResponseWrapper(localName = "ZPeEmpleadoPrestamosResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoPrestamosResponse")
    public TableOfZpeStEmpleadoPrestamos zPeEmpleadoPrestamos(
        @WebParam(name = "FechaInicioVacaciones", targetNamespace = "")
        String fechaInicioVacaciones,
        @WebParam(name = "Pernr", targetNamespace = "")
        String pernr);

}
