
package com.sap.document.sap.soap.functions.mc_style;

import com.sap.document.sap.rfc.functions.TABLEOFZPESTEMPLEADOJORNADADIARIA;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_EMPLEADO_JORNADA_DIARI", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    com.sap.document.sap.rfc.functions.ObjectFactory.class,
    com.sap.document.sap.soap.functions.mc_style.ObjectFactory.class
})
public interface ZWSPEEMPLEADOJORNADADIARI {


    /**
     * 
     * @param imPernr
     * @param imInicio
     * @param imFin
     * @return
     *     returns com.sap.document.sap.rfc.functions.TABLEOFZPESTEMPLEADOJORNADADIARIA
     */
    @WebMethod(operationName = "ZPeEmpleadoJornadaDiaria", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_EMPLEADO_jornada_diari:ZPeEmpleadoJornadaDiariaRequest")
    @WebResult(name = "TEmpleados", targetNamespace = "")
    @RequestWrapper(localName = "ZPeEmpleadoJornadaDiaria", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoJornadaDiaria")
    @ResponseWrapper(localName = "ZPeEmpleadoJornadaDiariaResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoJornadaDiariaResponse")
    public TABLEOFZPESTEMPLEADOJORNADADIARIA zPeEmpleadoJornadaDiaria(
        @WebParam(name = "ImFin", targetNamespace = "")
        String imFin,
        @WebParam(name = "ImInicio", targetNamespace = "")
        String imInicio,
        @WebParam(name = "ImPernr", targetNamespace = "")
        String imPernr);

}
