
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_PROCESOS_SELECCION_INS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSPEPROCESOSSELECCIONINS {


    /**
     * 
     * @param imEsEmpleado
     * @param imProcId
     * @param exReturn
     * @param imVacId
     * @param imNumCand
     * @param exNumCand
     * @param imCupoDisc
     */
    @WebMethod(operationName = "ZPeProcesosSeleccionInscri", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_PROCESOS_SELECCION_INS:ZPeProcesosSeleccionInscriRequest")
    @RequestWrapper(localName = "ZPeProcesosSeleccionInscri", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeProcesosSeleccionInscri")
    @ResponseWrapper(localName = "ZPeProcesosSeleccionInscriResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeProcesosSeleccionInscriResponse")
    public void zPeProcesosSeleccionInscri(
        @WebParam(name = "ImCupoDisc", targetNamespace = "")
        String imCupoDisc,
        @WebParam(name = "ImEsEmpleado", targetNamespace = "")
        String imEsEmpleado,
        @WebParam(name = "ImNumCand", targetNamespace = "")
        String imNumCand,
        @WebParam(name = "ImProcId", targetNamespace = "")
        String imProcId,
        @WebParam(name = "ImVacId", targetNamespace = "")
        String imVacId,
        @WebParam(name = "ExNumCand", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> exNumCand,
        @WebParam(name = "ExReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Bapireturn1> exReturn);

}
