
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_CIERTOS_DATOS_ESTRUCTU", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSPECIERTOSDATOSESTRUCTU {


    /**
     * 
     * @param consejeroId
     * @param direccionRrhhRespId
     * @param divisionRrhhRespId
     * @param subdireccionRrhhRespId
     * @param presidentePpeId
     */
    @WebMethod(operationName = "ZPeCiertosDatosEstructura", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_CIERTOS_DATOS_ESTRUCTU:ZPeCiertosDatosEstructuraRequest")
    @RequestWrapper(localName = "ZPeCiertosDatosEstructura", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeCiertosDatosEstructura")
    @ResponseWrapper(localName = "ZPeCiertosDatosEstructuraResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeCiertosDatosEstructuraResponse")
    public void zPeCiertosDatosEstructura(
        @WebParam(name = "ConsejeroId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> consejeroId,
        @WebParam(name = "DireccionRrhhRespId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> direccionRrhhRespId,
        @WebParam(name = "DivisionRrhhRespId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> divisionRrhhRespId,
        @WebParam(name = "PresidentePpeId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> presidentePpeId,
        @WebParam(name = "SubdireccionRrhhRespId", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> subdireccionRrhhRespId);

}
