
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_SUBORDINADOS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSPESUBORDINADOS {


    /**
     * 
     * @param directosTodos
     * @param pernr
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.TableOfZpeStSubordinados
     */
    @WebMethod(operationName = "ZPeSubordinados", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_SUBORDINADOS:ZPeSubordinadosRequest")
    @WebResult(name = "TEmpleados", targetNamespace = "")
    @RequestWrapper(localName = "ZPeSubordinados", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeSubordinados")
    @ResponseWrapper(localName = "ZPeSubordinadosResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeSubordinadosResponse")
    public TableOfZpeStSubordinados zPeSubordinados(
        @WebParam(name = "DirectosTodos", targetNamespace = "")
        String directosTodos,
        @WebParam(name = "Pernr", targetNamespace = "")
        String pernr);

}
