
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Z_WS_PE_EMPLEADO_HIST_CONTR_CA", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSPEEMPLEADOHISTCONTRCA {


    /**
     * 
     * @param tHistContrCategResumen
     * @param tHistContrCategDesglose
     * @param pernr
     */
    @WebMethod(operationName = "ZPeEmpleadoHistContrCateg", action = "urn:sap-com:document:sap:soap:functions:mc-style:Z_WS_PE_EMPLEADO_HIST_CONTR_CA:ZPeEmpleadoHistContrCategRequest")
    @RequestWrapper(localName = "ZPeEmpleadoHistContrCateg", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoHistContrCateg")
    @ResponseWrapper(localName = "ZPeEmpleadoHistContrCategResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZPeEmpleadoHistContrCategResponse")
    public void zPeEmpleadoHistContrCateg(
        @WebParam(name = "Pernr", targetNamespace = "")
        String pernr,
        @WebParam(name = "THistContrCategDesglose", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEmpleadoHistContrCat> tHistContrCategDesglose,
        @WebParam(name = "THistContrCategResumen", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TableOfZpeStEmpleadoHistContrCat> tHistContrCategResumen);

}
