
package com.sap.document.sap.soap.functions.mc_style;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_SUBORDINADOS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:META-INF/wsdl/Z_WS_PE_SUBORDINADOS.wsdl")
public class ZWSPESUBORDINADOS_Service
    extends Service
{

    private final static URL ZWSPESUBORDINADOS_WSDL_LOCATION;
    private final static WebServiceException ZWSPESUBORDINADOS_EXCEPTION;
    private final static QName ZWSPESUBORDINADOS_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_SUBORDINADOS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/Z_WS_PE_SUBORDINADOS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPESUBORDINADOS_WSDL_LOCATION = url;
        ZWSPESUBORDINADOS_EXCEPTION = e;
    }

    public ZWSPESUBORDINADOS_Service() {
        super(__getWsdlLocation(), ZWSPESUBORDINADOS_QNAME);
    }

    public ZWSPESUBORDINADOS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPESUBORDINADOS_QNAME, features);
    }

    public ZWSPESUBORDINADOS_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPESUBORDINADOS_QNAME);
    }

    public ZWSPESUBORDINADOS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPESUBORDINADOS_QNAME, features);
    }

    public ZWSPESUBORDINADOS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPESUBORDINADOS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPESUBORDINADOS
     */
    @WebEndpoint(name = "Z_WS_PE_SUBORDINADOS")
    public ZWSPESUBORDINADOS getZWSPESUBORDINADOS() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_SUBORDINADOS"), ZWSPESUBORDINADOS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPESUBORDINADOS
     */
    @WebEndpoint(name = "Z_WS_PE_SUBORDINADOS")
    public ZWSPESUBORDINADOS getZWSPESUBORDINADOS(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_SUBORDINADOS"), ZWSPESUBORDINADOS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPESUBORDINADOS_EXCEPTION!= null) {
            throw ZWSPESUBORDINADOS_EXCEPTION;
        }
        return ZWSPESUBORDINADOS_WSDL_LOCATION;
    }

}
