
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_EMPLEADO_HIST_TITULACI", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/C:/Dev/INTEMASESA/modules/custom/sap-integration-services/src/main/resources/META-INF/wsdl/z_ws_pe_empleado_hist_titulaci.wsdl")
public class ZWSPEEMPLEADOHISTTITULACI_Service
    extends Service
{

    private final static URL ZWSPEEMPLEADOHISTTITULACI_WSDL_LOCATION;
    private final static WebServiceException ZWSPEEMPLEADOHISTTITULACI_EXCEPTION;
    private final static QName ZWSPEEMPLEADOHISTTITULACI_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_TITULACI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Dev/INTEMASESA/modules/custom/sap-integration-services/src/main/resources/META-INF/wsdl/z_ws_pe_empleado_hist_titulaci.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPEEMPLEADOHISTTITULACI_WSDL_LOCATION = url;
        ZWSPEEMPLEADOHISTTITULACI_EXCEPTION = e;
    }

    public ZWSPEEMPLEADOHISTTITULACI_Service() {
        super(__getWsdlLocation(), ZWSPEEMPLEADOHISTTITULACI_QNAME);
    }

    public ZWSPEEMPLEADOHISTTITULACI_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPEEMPLEADOHISTTITULACI_QNAME, features);
    }

    public ZWSPEEMPLEADOHISTTITULACI_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPEEMPLEADOHISTTITULACI_QNAME);
    }

    public ZWSPEEMPLEADOHISTTITULACI_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPEEMPLEADOHISTTITULACI_QNAME, features);
    }

    public ZWSPEEMPLEADOHISTTITULACI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPEEMPLEADOHISTTITULACI_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPEEMPLEADOHISTTITULACI
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_HIST_TITULACI")
    public ZWSPEEMPLEADOHISTTITULACI getZWSPEEMPLEADOHISTTITULACI() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_TITULACI"), ZWSPEEMPLEADOHISTTITULACI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPEEMPLEADOHISTTITULACI
     */
    @WebEndpoint(name = "Z_WS_PE_EMPLEADO_HIST_TITULACI")
    public ZWSPEEMPLEADOHISTTITULACI getZWSPEEMPLEADOHISTTITULACI(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_EMPLEADO_HIST_TITULACI"), ZWSPEEMPLEADOHISTTITULACI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPEEMPLEADOHISTTITULACI_EXCEPTION!= null) {
            throw ZWSPEEMPLEADOHISTTITULACI_EXCEPTION;
        }
        return ZWSPEEMPLEADOHISTTITULACI_WSDL_LOCATION;
    }

}
