
package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Z_WS_PE_CONSULTA_CERT_RET_PDF", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "classpath:META-INF/wsdl/z_ws_pe_consulta_cert_ret_pdf.wsdl")
public class ZWSPECONSULTACERTRETPDF_Service
    extends Service
{

    private final static URL ZWSPECONSULTACERTRETPDF_WSDL_LOCATION;
    private final static WebServiceException ZWSPECONSULTACERTRETPDF_EXCEPTION;
    private final static QName ZWSPECONSULTACERTRETPDF_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_CONSULTA_CERT_RET_PDF");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:META-INF/wsdl/z_ws_pe_consulta_cert_ret_pdf.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSPECONSULTACERTRETPDF_WSDL_LOCATION = url;
        ZWSPECONSULTACERTRETPDF_EXCEPTION = e;
    }

    public ZWSPECONSULTACERTRETPDF_Service() {
        super(__getWsdlLocation(), ZWSPECONSULTACERTRETPDF_QNAME);
    }

    public ZWSPECONSULTACERTRETPDF_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWSPECONSULTACERTRETPDF_QNAME, features);
    }

    public ZWSPECONSULTACERTRETPDF_Service(URL wsdlLocation) {
        super(wsdlLocation, ZWSPECONSULTACERTRETPDF_QNAME);
    }

    public ZWSPECONSULTACERTRETPDF_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWSPECONSULTACERTRETPDF_QNAME, features);
    }

    public ZWSPECONSULTACERTRETPDF_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWSPECONSULTACERTRETPDF_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSPECONSULTACERTRETPDF
     */
    @WebEndpoint(name = "Z_WS_PE_CONSULTA_CERT_RET_PDF")
    public ZWSPECONSULTACERTRETPDF getZWSPECONSULTACERTRETPDF() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_CONSULTA_CERT_RET_PDF"), ZWSPECONSULTACERTRETPDF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSPECONSULTACERTRETPDF
     */
    @WebEndpoint(name = "Z_WS_PE_CONSULTA_CERT_RET_PDF")
    public ZWSPECONSULTACERTRETPDF getZWSPECONSULTACERTRETPDF(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "Z_WS_PE_CONSULTA_CERT_RET_PDF"), ZWSPECONSULTACERTRETPDF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWSPECONSULTACERTRETPDF_EXCEPTION!= null) {
            throw ZWSPECONSULTACERTRETPDF_EXCEPTION;
        }
        return ZWSPECONSULTACERTRETPDF_WSDL_LOCATION;
    }

}
