
package juntadeandalucia.cice.pfirma.modify.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import juntadeandalucia.cice.pfirma.type.v2.Document;
import juntadeandalucia.cice.pfirma.type.v2.Request;
import juntadeandalucia.cice.pfirma.type.v2.RequestSign;
import juntadeandalucia.cice.pfirma.type.v2.SignerList;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ModifyService", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:v2.0")
@XmlSeeAlso({
    juntadeandalucia.cice.pfirma.modify.request.v2.ObjectFactory.class,
    juntadeandalucia.cice.pfirma.type.v2.ObjectFactory.class
})
public interface ModifyService {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     * @throws PfirmaException
     */
    @WebMethod
    @WebResult(name = "requestId", targetNamespace = "")
    @RequestWrapper(localName = "createRequest", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.CreateRequest")
    @ResponseWrapper(localName = "createRequestResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.CreateRequestResponse")
    public String createRequest(
        @WebParam(name = "request", targetNamespace = "")
        Request request)
        throws PfirmaException
    ;

    /**
     * 
     * @param requestSign
     * @return
     *     returns java.lang.String
     * @throws PfirmaException
     */
    @WebMethod
    @WebResult(name = "requestId", targetNamespace = "")
    @RequestWrapper(localName = "createRequestFromSign", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.CreateRequestFromSign")
    @ResponseWrapper(localName = "createRequestFromSignResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.CreateRequestFromSignResponse")
    public String createRequestFromSign(
        @WebParam(name = "requestSign", targetNamespace = "")
        RequestSign requestSign)
        throws PfirmaException
    ;

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     * @throws PfirmaException
     */
    @WebMethod
    @WebResult(name = "requestId", targetNamespace = "")
    @RequestWrapper(localName = "updateRequest", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.UpdateRequest")
    @ResponseWrapper(localName = "updateRequestResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.UpdateRequestResponse")
    public String updateRequest(
        @WebParam(name = "request", targetNamespace = "")
        Request request)
        throws PfirmaException
    ;

    /**
     * 
     * @param requestId
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteRequest", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.DeleteRequest")
    @ResponseWrapper(localName = "deleteRequestResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.DeleteRequestResponse")
    public void deleteRequest(
        @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> requestId)
        throws PfirmaException
    ;

    /**
     * 
     * @param requestId
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "sendRequest", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.SendRequest")
    @ResponseWrapper(localName = "sendRequestResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.SendRequestResponse")
    public void sendRequest(
        @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> requestId)
        throws PfirmaException
    ;

    /**
     * 
     * @param requestId
     * @param document
     * @return
     *     returns java.lang.String
     * @throws PfirmaException
     */
    @WebMethod
    @WebResult(name = "documentId", targetNamespace = "")
    @RequestWrapper(localName = "insertDocument", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.InsertDocument")
    @ResponseWrapper(localName = "insertDocumentResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.InsertDocumentResponse")
    public String insertDocument(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "document", targetNamespace = "")
        Document document)
        throws PfirmaException
    ;

    /**
     * 
     * @param documentId
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDocument", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.DeleteDocument")
    @ResponseWrapper(localName = "deleteDocumentResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.DeleteDocumentResponse")
    public void deleteDocument(
        @WebParam(name = "documentId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> documentId)
        throws PfirmaException
    ;

    /**
     * 
     * @param signerList
     * @param requestId
     * @param signLine
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "insertSigners", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.InsertSigners")
    @ResponseWrapper(localName = "insertSignersResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.InsertSignersResponse")
    public void insertSigners(
        @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> requestId,
        @WebParam(name = "signLine", targetNamespace = "")
        int signLine,
        @WebParam(name = "signerList", targetNamespace = "")
        SignerList signerList)
        throws PfirmaException
    ;

    /**
     * 
     * @param signerList
     * @param requestId
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSigners", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.DeleteSigners")
    @ResponseWrapper(localName = "deleteSignersResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.DeleteSignersResponse")
    public void deleteSigners(
        @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> requestId,
        @WebParam(name = "signerList", targetNamespace = "")
        SignerList signerList)
        throws PfirmaException
    ;

    /**
     * 
     * @param accessLevel
     * @param requestId
     * @param documentId
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "updateDocumentAccess", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.UpdateDocumentAccess")
    @ResponseWrapper(localName = "updateDocumentAccessResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.UpdateDocumentAccessResponse")
    public void updateDocumentAccess(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "documentId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> documentId,
        @WebParam(name = "accessLevel", targetNamespace = "")
        String accessLevel)
        throws PfirmaException
    ;

    /**
     * 
     * @param date
     * @param requestId
     * @throws PfirmaException
     */
    @WebMethod
    @RequestWrapper(localName = "updateDateNextSigner", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.UpdateDateNextSigner")
    @ResponseWrapper(localName = "updateDateNextSignerResponse", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:request:v2.0", className = "juntadeandalucia.cice.pfirma.modify.request.v2.UpdateDateNextSignerResponse")
    public void updateDateNextSigner(
        @WebParam(name = "requestId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> requestId,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date)
        throws PfirmaException
    ;

}
