
package juntadeandalucia.cice.pfirma.modify.v2;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ModifyServiceService", targetNamespace = "urn:juntadeandalucia:cice:pfirma:modify:v2.0", wsdlLocation = "META-INF/wsdl/ModifyService.wsdl")
public class ModifyServiceService
    extends Service
{

    private final static URL MODIFYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MODIFYSERVICESERVICE_EXCEPTION;
    private final static QName MODIFYSERVICESERVICE_QNAME = new QName("urn:juntadeandalucia:cice:pfirma:modify:v2.0", "ModifyServiceService");

    static {
        MODIFYSERVICESERVICE_WSDL_LOCATION = juntadeandalucia.cice.pfirma.modify.v2.ModifyServiceService.class.getClassLoader().getResource("META-INF/wsdl/ModifyService.wsdl");
        WebServiceException e = null;
        if (MODIFYSERVICESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/ModifyService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        MODIFYSERVICESERVICE_EXCEPTION = e;
    }

    public ModifyServiceService() {
        super(__getWsdlLocation(), MODIFYSERVICESERVICE_QNAME);
    }

    public ModifyServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODIFYSERVICESERVICE_QNAME, features);
    }

    public ModifyServiceService(URL wsdlLocation) {
        super(wsdlLocation, MODIFYSERVICESERVICE_QNAME);
    }

    public ModifyServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODIFYSERVICESERVICE_QNAME, features);
    }

    public ModifyServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModifyServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModifyService
     */
    @WebEndpoint(name = "ModifyServicePort")
    public ModifyService getModifyServicePort() {
        return super.getPort(new QName("urn:juntadeandalucia:cice:pfirma:modify:v2.0", "ModifyServicePort"), ModifyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModifyService
     */
    @WebEndpoint(name = "ModifyServicePort")
    public ModifyService getModifyServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:juntadeandalucia:cice:pfirma:modify:v2.0", "ModifyServicePort"), ModifyService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODIFYSERVICESERVICE_EXCEPTION!= null) {
            throw MODIFYSERVICESERVICE_EXCEPTION;
        }
        return MODIFYSERVICESERVICE_WSDL_LOCATION;
    }

}
