
package com.espiralms.paw;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * Servicios web de ProactivaNET ®
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ProactivaNETServices", targetNamespace = "http://www.espiralms.com/paw", wsdlLocation = "META-INF/wsdl/externalservices.wsdl")
public class ProactivaNETServices
    extends Service
{

    private final static URL PROACTIVANETSERVICES_WSDL_LOCATION;
    private final static WebServiceException PROACTIVANETSERVICES_EXCEPTION;
    private final static QName PROACTIVANETSERVICES_QNAME = new QName("http://www.espiralms.com/paw", "ProactivaNETServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("META-INF/wsdl/externalservices.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROACTIVANETSERVICES_WSDL_LOCATION = url;
        PROACTIVANETSERVICES_EXCEPTION = e;
    }

    public ProactivaNETServices() {
        super(__getWsdlLocation(), PROACTIVANETSERVICES_QNAME);
    }

    public ProactivaNETServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROACTIVANETSERVICES_QNAME, features);
    }

    public ProactivaNETServices(URL wsdlLocation) {
        super(wsdlLocation, PROACTIVANETSERVICES_QNAME);
    }

    public ProactivaNETServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROACTIVANETSERVICES_QNAME, features);
    }

    public ProactivaNETServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProactivaNETServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProactivaNETServicesSoap
     */
    @WebEndpoint(name = "ProactivaNETServicesSoap")
    public ProactivaNETServicesSoap getProactivaNETServicesSoap() {
        return super.getPort(new QName("http://www.espiralms.com/paw", "ProactivaNETServicesSoap"), ProactivaNETServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProactivaNETServicesSoap
     */
    @WebEndpoint(name = "ProactivaNETServicesSoap")
    public ProactivaNETServicesSoap getProactivaNETServicesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.espiralms.com/paw", "ProactivaNETServicesSoap"), ProactivaNETServicesSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROACTIVANETSERVICES_EXCEPTION!= null) {
            throw PROACTIVANETSERVICES_EXCEPTION;
        }
        return PROACTIVANETSERVICES_WSDL_LOCATION;
    }

}
